# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ef2d9161b837a647d69cc515aa474c3a4d6617daaf2a9b9c7cff02ca4e3929b721035edc1591d7ef6557226d4965141c4633200e0c1245b7e6b4ebde332cc0

test:
  secret_key_base: 80e49a91396d3186f5da7d839a92c65206c06c22c3f2fb55d43127ee0d433b9c2be55f6cac0aa34657f2cdfae0f574f888fecdda74e2ac6f8fd301313991b019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
